import {
  Check,
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  Unique,
  UpdateDateColumn,
} from 'typeorm';
import { Shift } from '../shifts/shift.entity';
import { Supplier } from '../suppliers/supplier.entity';
import { User } from '../users/user.entity';
import { CrateIssuanceMode } from './crate-issuance-mode.enum';

/**
 * Crates handed to a supplier. Like `intakes` and `payouts`, it stores neither
 * the point nor the business date — both come from `shift_id` (§2.3).
 *
 * THE TRANCHE. A return consumes issuances oldest-first and copies `per_unit`
 * from the one it consumes, so this row is what makes «людина, яка брала по 120
 * і по 130, отримує назад саме те, що платила» true (§6.5).
 *
 * `deposit_per_unit` IS A SNAPSHOT (§2.7). Repricing the crate in the catalogue
 * does not touch a July issuance — ticket #60: «якщо хтось взяв ящики за 120
 * гривень кожен, то повертає він також за 120 гривень кожен ящик».
 *
 * THERE IS NO `remaining_units`. It is derived as `units − Σ allocations from
 * non-voided returns`, for the reason `intakes` has no stored `remaining`
 * (§3.2): a stored balance is a second copy of a fact.
 *
 * NO `tare_type_id`, AND THAT IS A DECISION (spec §4.2). The facility rents one
 * standard crate; the catalogue's variety serves the berry side alone. Which
 * catalogue row IS that crate is `tare_types.is_crate`, which is exclusive.
 */
@Entity('crate_issuances')
@Unique('UQ_crate_issuances_code', ['code'])
@Check('CHK_crate_issuances_units', `"units" > 0`)
@Check('CHK_crate_issuances_deposit_per_unit', `"deposit_per_unit" >= 0`)
@Check('CHK_crate_issuances_deposit_taken', `"deposit_taken" >= 0`)
@Check(
  'CHK_crate_issuances_receipt_no_money',
  `"mode" <> 'receipt' OR ("deposit_per_unit" = 0 AND "deposit_taken" = 0)`,
)
@Check(
  'CHK_crate_issuances_void_trio',
  `num_nulls("voided_at", "voided_by_user_id", "void_reason") IN (0, 3)`,
)
@Index('IDX_crate_issuances_supplier_created', ['supplier_id', 'created_at'])
@Index('IDX_crate_issuances_shift_mode', ['shift_id', 'mode'])
export class CrateIssuance {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** `{POINT}-{CR|CD}-{YYYYMMDD}-{NNN}`, GENERATED by the server — see
   *  `crate-code.ts`. The operator copies it onto the paper розписка; for a
   *  deposit issuance it is an internal identifier that reaches no paper. */
  @Column({ type: 'varchar' })
  code: string;

  @Column({ type: 'uuid' })
  shift_id: string;

  @ManyToOne(() => Shift, { onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'shift_id' })
  shift?: Shift;

  @Column({ type: 'uuid' })
  supplier_id: string;

  @ManyToOne(() => Supplier, { onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'supplier_id' })
  supplier?: Supplier;

  @Column({ type: 'int' })
  units: number;

  @Column({ type: 'enum', enum: CrateIssuanceMode, enumName: 'crate_issuance_mode' })
  mode: CrateIssuanceMode;

  /** `numeric` — a STRING, never a number. Zero for a receipt issuance, by CHECK. */
  @Column({ type: 'numeric', precision: 12, scale: 2, default: 0 })
  deposit_per_unit: string;

  @Column({ type: 'numeric', precision: 12, scale: 2, default: 0 })
  deposit_taken: string;

  /** §10.6 — «підпис під документом належить тому, хто натиснув». */
  @Column({ type: 'uuid' })
  issued_by_user_id: string;

  @ManyToOne(() => User, { onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'issued_by_user_id' })
  issued_by?: User;

  @Column({ type: 'timestamptz', nullable: true })
  voided_at: Date | null;

  @Column({ type: 'uuid', nullable: true })
  voided_by_user_id: string | null;

  @Column({ type: 'text', nullable: true })
  void_reason: string | null;

  @CreateDateColumn({ type: 'timestamptz' })
  created_at: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updated_at: Date;
}
